apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: newdevops
  name: newdevops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newdevops
  template:
    metadata:
      labels:
        app: newdevops
    spec:
      containers:
      - name: newdevops
        image: anandhakumarkj/devopsproject
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
